"""Deterministic default-voice assignment (Resolved Decision RD-2).

Every character gets one built-in voice per engine. Nothing is cloned and no
model is loaded: the assignment is a pure function of ``CAST.md`` plus the
static voice catalog, so ``presets.yaml`` can be regenerated byte-identically
on any machine.

Assignment rules
----------------
1. **Gender** is read off ``voicePrompt`` in strict priority order — an explicit
   gender word beats a character-name hint, which beats a voice-type word
   (bass/alto/...), which beats a low-register pitch cue. PRINCIPAL is the
   reason for that ordering: her prompt says *"Female, a gravelly, lilting
   baritone"*, and the explicit word must win.
2. **Age band** is ``child`` / ``elder`` / ``adult``, from explicit cues only.
   "boy" is deliberately NOT a child cue (LEROY's prompt mentions "the Rhodes
   boy"), and "older" is not an elder cue (CYRUS is an "older brother").
3. Single-voice engines (chatterbox, chatterbox-turbo, soprano) give every
   character the same built-in voice.
4. Multi-voice engines (qwen3) build a candidate list of the assignable voices
   matching the character's gender, ordered by ``_AGE_PREFERENCE`` (exact age
   band first, then the least-bad fallback), and hand out
   ``candidates[n % len(candidates)]`` where ``n`` counts the
   characters already placed in that (gender, age band) bucket, in ``CAST.md``
   order. That spreads the small preset pool evenly and keeps neighbouring
   characters on different voices.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from . import catalog
from .catalog import ENGINES, Engine
from .roster import CastMember, Roster

SCHEMA_VERSION = 1
PRESETS_FILENAME = "presets.yaml"

# --- classification ----------------------------------------------------------

_FEMALE_EXPLICIT = re.compile(r"\b(female|woman|women|girl|she|her)\b", re.I)
_MALE_EXPLICIT = re.compile(r"\b(male|man|men|boy|he|his)\b", re.I)
_FEMALE_NAME_HINT = re.compile(r"\b(mom|mother|mrs|ms|miss|aunt|grandma|woman|girl|lady)\b", re.I)
_MALE_NAME_HINT = re.compile(r"\b(mr|dad|father|uncle|grandpa|man|boy)\b", re.I)
_FEMALE_VOICE_TYPE = re.compile(r"\b(soprano|mezzo|alto|contralto)\b", re.I)
_MALE_VOICE_TYPE = re.compile(r"\b(bass|basso|baritone|tenor)\b", re.I)
_MALE_PITCH_CUE = re.compile(r"\b(low|deep|subterranean)\b", re.I)

_CHILD_CUE = re.compile(r"\b(child|treble|\d{1,2} years old|unbroken)\b", re.I)
_ELDER_CUE = re.compile(
    r"(\b[6-9]0s\b|\b\d{2}\+|\belderly\b|\bold (?:man|woman)\b|wisdom of age|\bseasoned\b)",
    re.I,
)


@dataclass(frozen=True)
class Classification:
    gender: str
    gender_source: str
    age_band: str
    age_source: str


def classify(member: CastMember) -> Classification:
    """Infer gender and age band from a cast member's prompt and name."""
    prompt = member.voice_prompt or ""
    name = member.character

    gender, gender_source = "neutral", "fallback:no-cue"
    if _FEMALE_EXPLICIT.search(prompt):
        gender, gender_source = "female", "prompt:explicit-gender-word"
    elif _MALE_EXPLICIT.search(prompt):
        gender, gender_source = "male", "prompt:explicit-gender-word"
    elif _FEMALE_NAME_HINT.search(name):
        gender, gender_source = "female", "character-name-hint"
    elif _MALE_NAME_HINT.search(name):
        gender, gender_source = "male", "character-name-hint"
    elif _FEMALE_VOICE_TYPE.search(prompt):
        gender, gender_source = "female", "prompt:voice-type-word"
    elif _MALE_VOICE_TYPE.search(prompt):
        gender, gender_source = "male", "prompt:voice-type-word"
    elif _MALE_PITCH_CUE.search(prompt):
        gender, gender_source = "male", "prompt:low-register-cue"

    age_band, age_source = "adult", "default"
    if _CHILD_CUE.search(prompt):
        age_band, age_source = "child", "prompt:child-cue"
    elif _ELDER_CUE.search(prompt):
        age_band, age_source = "elder", "prompt:elder-cue"

    return Classification(gender, gender_source, age_band, age_source)


# --- assignment --------------------------------------------------------------


@dataclass
class CharacterAssignment:
    character: str
    classification: Classification
    voxalta_paths: tuple[str, ...]
    #: engine key -> voice name (``None`` when the engine offers nothing usable)
    voices: dict[str, str | None] = field(default_factory=dict)
    notes: list[str] = field(default_factory=list)

    @property
    def resolved(self) -> bool:
        return bool(self.voices) and all(v for v in self.voices.values())

    @property
    def unresolved_engines(self) -> list[str]:
        return [key for key, voice in self.voices.items() if not voice]


@dataclass
class Assignments:
    roster: Roster
    engines: tuple[Engine, ...]
    characters: list[CharacterAssignment]

    @property
    def engine_keys(self) -> tuple[str, ...]:
        return tuple(e.key for e in self.engines)

    @property
    def unresolved(self) -> list[CharacterAssignment]:
        return [c for c in self.characters if not c.resolved]


#: For a character in age band X, the order in which voice age bands are tried.
#: A ten-year-old is better served by an adult voice than by an elderly one, so
#: the fallback order is explicit rather than "everything else in catalog order".
_AGE_PREFERENCE: dict[str, tuple[str, ...]] = {
    "child": ("child", "any", "adult", "elder"),
    "adult": ("adult", "any", "elder", "child"),
    "elder": ("elder", "any", "adult", "child"),
}


def _candidates(engine: Engine, cls: Classification) -> list[catalog.Voice]:
    """Ordered voice candidates for one character on one engine."""
    pool = [v for v in engine.assignable_voices if v.gender == cls.gender]
    if not pool:
        pool = list(engine.assignable_voices)
    order = _AGE_PREFERENCE.get(cls.age_band, _AGE_PREFERENCE["adult"])
    return sorted(
        pool,
        key=lambda v: order.index(v.age_band) if v.age_band in order else len(order),
    )


def assign(roster: Roster, engines: tuple[Engine, ...] = ENGINES) -> Assignments:
    """Assign a built-in voice per character per engine, deterministically."""
    counters: dict[tuple[str, str, str], int] = {}
    characters: list[CharacterAssignment] = []

    for member in roster.members:
        cls = classify(member)
        assignment = CharacterAssignment(
            character=member.character,
            classification=cls,
            voxalta_paths=member.voxalta_paths,
        )
        if not member.voice_prompt:
            assignment.notes.append("CAST.md entry has an empty voicePrompt")
        if cls.gender == "neutral":
            assignment.notes.append(
                "no gender cue in voicePrompt or character name; assigned from the full preset pool"
            )

        for engine in engines:
            if not engine.multi_voice:
                only = engine.assignable_voices[0] if engine.assignable_voices else None
                assignment.voices[engine.key] = only.name if only else None
                continue

            options = _candidates(engine, cls)
            if not options:
                assignment.voices[engine.key] = None
                continue

            key = (engine.key, cls.gender, cls.age_band)
            index = counters.get(key, 0)
            counters[key] = index + 1
            choice = options[index % len(options)]
            assignment.voices[engine.key] = choice.name

            if choice.age_band != cls.age_band and cls.age_band != "adult":
                assignment.notes.append(
                    f"{engine.key}: no {cls.age_band} preset available; "
                    f"fell back to the {choice.age_band} voice '{choice.name}'"
                )
            if choice.gender != cls.gender and cls.gender != "neutral":
                assignment.notes.append(
                    f"{engine.key}: no {cls.gender} preset available; used '{choice.name}'"
                )

        characters.append(assignment)

    return Assignments(roster=roster, engines=tuple(engines), characters=characters)


# --- presets.yaml ------------------------------------------------------------


def _home_relative(path: Path) -> str:
    try:
        return "~/" + str(path.resolve().relative_to(Path.home()))
    except ValueError:
        return str(path)


def to_document(assignments: Assignments) -> dict[str, Any]:
    """Build the ``presets.yaml`` document for a set of assignments.

    The document carries no timestamp on purpose: regenerating it from the same
    ``CAST.md`` must produce a byte-identical file so a stale ``presets.yaml``
    shows up as a real diff.
    """
    doc: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "generated_by": "comparativa voices --write",
        "policy": (
            "Round 1 is defaults-only (EXECUTION_PLAN.md RD-2): built-in/default voices "
            "only, auto-assigned from CAST.md voicePrompt keywords. voices.voxalta paths "
            "are recorded for the future cloning mission and are never opened."
        ),
        "source": {
            "project_dir": _home_relative(assignments.roster.project_dir),
            "cast_file": assignments.roster.cast_file.name,
            "cast_sha256": assignments.roster.cast_sha256,
            "cast_size": len(assignments.roster),
        },
        "engines": {},
        "assignments": {},
    }

    for engine in assignments.engines:
        entry: dict[str, Any] = {
            "checkpoint": engine.checkpoint,
            "role": engine.role,
            "multi_voice": engine.multi_voice,
            "voices_verified_locally": engine.voices_verified_locally,
            "voice_list_source": engine.source,
            "voices": [],
        }
        for voice in engine.voices:
            voice_entry: dict[str, Any] = {
                "name": voice.name,
                "gender": voice.gender,
                "age_band": voice.age_band,
                "language": voice.language,
                "assignable": voice.assignable,
            }
            if voice.note:
                voice_entry["note"] = voice.note
            entry["voices"].append(voice_entry)
        doc["engines"][engine.key] = entry

    for character in assignments.characters:
        record: dict[str, Any] = {
            "gender": character.classification.gender,
            "gender_source": character.classification.gender_source,
            "age_band": character.classification.age_band,
            "age_source": character.classification.age_source,
            "engines": dict(character.voices),
        }
        if character.voxalta_paths:
            record["voxalta"] = list(character.voxalta_paths)
        if character.notes:
            record["notes"] = list(character.notes)
        doc["assignments"][character.character] = record

    return doc


def dump_yaml(document: dict[str, Any]) -> str:
    """Serialize a presets document deterministically."""
    return yaml.safe_dump(document, sort_keys=False, width=100, allow_unicode=True)


def write_presets(assignments: Assignments, path: str | Path) -> Path:
    """Write ``presets.yaml`` and return the path written."""
    target = Path(path).expanduser()
    target.write_text(dump_yaml(to_document(assignments)), encoding="utf-8")
    return target


def load_presets(path: str | Path) -> dict[str, Any]:
    """Read a ``presets.yaml`` document."""
    return yaml.safe_load(Path(path).expanduser().read_text(encoding="utf-8"))


def voice_for(document: dict[str, Any], character: str, engine_key: str) -> str | None:
    """Look up one character's assigned voice for one engine."""
    record = (document.get("assignments") or {}).get(character)
    if not record:
        return None
    return (record.get("engines") or {}).get(engine_key)
